### ISSUE TITLE
Setup settings for company

### ISSUE THREAD

**Issue by MohammedAlNazili** [frappe/books#1064]
<h2>Description</h2>
when adding address from a short insert  with Arabic string 

<h2>Steps to Reproduce</h2>
from getting started for setting up company info 
adding address for company show ...
<h2>Info</h2>

**Error**: _NotFoundError: Not Found: Address نقم - شارع برلين_

**Stack**:
```
NotFoundError: Not Found: Address نقم - شارع برلين
    at Proxy.load (http://127.0.0.1:6969/@fs/home/malnozili/frappebooks/books/fyo/model/doc.ts:442:13)
    at async DocHandler.getDoc (http://127.0.0.1:6969/@fs/home/malnozili/frappebooks/books/fyo/core/docHandler.ts:56:5)
    at async Proxy._loadLinkDoc (http://127.0.0.1:6969/@fs/home/malnozili/frappebooks/books/fyo/model/doc.ts:483:29)
    at async Proxy._loadLinkField (http://127.0.0.1:6969/@fs/home/malnozili/frappebooks/books/fyo/model/doc.ts:471:5)
    at async Proxy._loadLink (http://127.0.0.1:6969/@fs/home/malnozili/frappebooks/books/fyo/model/doc.ts:459:14)
    at async Proxy.loadLinks (http://127.0.0.1:6969/@fs/home/malnozili/frappebooks/books/fyo/model/doc.ts:454:7)
    at async Proxy.loadAndGetLink (http://127.0.0.1:6969/@fs/home/malnozili/frappebooks/books/fyo/model/doc.ts:493:7)
    at async Proxy.setLinkValue (http://127.0.0.1:6969/components/Controls/Link.vue:50:23)
```

**Version**: `0.25.0`
**Platform**: `linux`
**Path**: `/settings?tab=PrintSettings`
**Language**: `English`
**Country**: `ye`

**Comment by akshayitzme** [comment]
@MohammedAlNazili 
I couldn't reproduce the issue in the latest version. Could you check it from your end ?

**Comment by akshayitzme** [comment]
Closing due to lack of response
