### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ashish-greycube** [frappe/books#328]
`yarn electron:serve`

```
Launching Electron...
(node:284025) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/ashish/mobile/books/dist_electron/package.json' of 'background.js'. Please either fix that or report it to the module author
(Use `electron --trace-deprecation ...` to show where the warning was created)
(node:284025) ExtensionLoadWarning: Warnings loading extension at /home/ashish/.config/frappe-books/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

```
![image](https://user-images.githubusercontent.com/29812965/151656838-bd711822-5489-4325-a9bd-7cc3486786b3.png)

@18alantom  pl pl help or give some pointer

**Comment by ankitsinghaniyaz** [comment]
@ashish-greycube is the app starting for you or crashing? I read that there's some exception but can you elaborate on what is happening?

**Comment by ashish-greycube** [comment]
runing with node 17.4.0 gave following exceptions
```
ashish@XPS15:~/mobile/books$ yarn electron:serve
yarn run v1.22.17
warning ../package.json: No license field
$ vue-cli-service electron:serve
 INFO  Starting development server...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
Starting type checking service...
Using 1 worker with 2048MB memory limit
10% building 4/6 modules 2 active ...vue/cli-plugin-babel/node_modules/cache-loader/dist/cjs.js??ref--13-0!/home/ashish/mobile/books/node_modules/babel-loader/lib/index.js!/home/ashish/mobile/books/src/print.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/ashish/mobile/books/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/ashish/mobile/books/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/ashish/mobile/books/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/ashish/mobile/books/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
10% building 4/8 modules 4 active /home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/hot/dev-server.js/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/ashish/mobile/books/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/home/ashish/mobile/books/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/ashish/mobile/books/node_modules/@vue/cli-plugin-babel/node_modules/cache-loader/dist/index.js:240:7
    at /home/ashish/mobile/books/node_modules/neo-async/async.js:2830:7
    at done (/home/ashish/mobile/books/node_modules/neo-async/async.js:2865:11)
    at /home/ashish/mobile/books/node_modules/neo-async/async.js:2818:7
    at Array.<anonymous> (/home/ashish/mobile/books/node_modules/@vue/cli-plugin-babel/node_modules/cache-loader/dist/index.js:229:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
so i switched to node 16.13.1 and ran again
after that it does run..but on command prompt i get following errors

```
ashish@XPS15:~/mobile/books$ yarn electron:serve
yarn run v1.22.17
warning ../package.json: No license field
$ vue-cli-service electron:serve
 INFO  Starting development server...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
Starting type checking service...
Using 1 worker with 2048MB memory limit
98% after emitting CopyPlugin

 WARNING  Compiled with 1 warning                                                                                                                                                                        9:39:14 AM

 warning  in ./node_modules/knex/lib/migrations/util/import-file.js

Critical dependency: the request of a dependency is an expression

No type errors found
Version: typescript 4.1.6
Time: 5509ms

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.65.22.165:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

⠇  Bundling main process...

 DONE  Compiled successfully in 7493ms                                                                                                                                                                   9:39:22 AM

  File                      Size                                                                                      Gzipped

  dist_electron/index.js    2324.00 KiB                                                                               414.70 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
(node:304945) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/ashish/mobile/books/dist_electron/package.json' of 'background.js'. Please either fix that or report it to the module author
(Use `electron --trace-deprecation ...` to show where the warning was created)
(node:304945) ExtensionLoadWarning: Warnings loading extension at /home/ashish/.config/frappe-books/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

```

**Comment by 18alantom** [comment]
This is expected.
- 1st is due to `knex` one of the dependencies, nothing that can be done besides forking and fixing and using the fork.
- 2nd is due to` background.js` being the main process file instead of `main.js`
- 3rd is some junk electron output, there are no files starting with `_` in the Repo

As long as everything else is running it's fine, feel free to comment if it isn't.

Closing cause expected output.
