### ISSUE TITLE
unable to successfully perform ` yarn install `

### ISSUE THREAD

**Issue by jaffreyjoy** [frappe/books#33]
### Tried to perform `yarn install` but got the following error : 
![image](https://user-images.githubusercontent.com/20588777/38531493-abb32266-3c8d-11e8-8e8b-e409aac334ad.png)

#### Complete error log :
```
Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.9.4 | win32 | x64
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and electron@1.8.4 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Jaffrey Joy\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\nvm\v8.9.4\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\nvm\v8.9.4\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\nvm\v8.9.4\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=H:\\GitHub clones\\accounting\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=H:\\GitHub clones\\accounting\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64"
gyp ERR! cwd H:\GitHub clones\accounting\node_modules\sqlite3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=H:\GitHub clones\accounting\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=H:\GitHub clones\accounting\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (H:\GitHub clones\accounting\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "H:\\GitHub clones\\accounting\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd H:\GitHub clones\accounting\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node-pre-gyp install --fallback-to-build
Directory: H:\\GitHub clones\\accounting\
ode_modules\\sqlite3
Output:
".

    at ChildProcess.childProcess.once.code (H:\GitHub clones\accounting\node_modules\electron-builder-lib\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at H:\GitHub clones\accounting\node_modules\electron-builder-lib\src\util\yarn.ts:149:27
From previous event:
    at rebuild (H:\GitHub clones\accounting\node_modules\electron-builder-lib\out\util\yarn.js:233:18)
    at H:\GitHub clones\accounting\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at installOrRebuild (H:\GitHub clones\accounting\node_modules\electron-builder-lib\out\util\yarn.js:68:17)
    at H:\GitHub clones\accounting\node_modules\electron-builder\src\cli\install-app-deps.ts:57:5
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (H:\GitHub clones\accounting\node_modules\electron-builder\out\cli\install-app-deps.js:174:17)
    at then (H:\GitHub clones\accounting\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (H:\GitHub clones\accounting\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at Object.runCommand (H:\GitHub clones\accounting\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (H:\GitHub clones\accounting\node_modules\yargs\yargs.js:1014:30)
    at Object.get [as argv] (H:\GitHub clones\accounting\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (H:\GitHub clones\accounting\node_modules\electron-builder\src\cli\cli.ts:28:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c electron-builder install-app-deps
Directory: H:\\GitHub clones\\accounting
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "H:\\GitHub clones\\accounting\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

#### Steps to reproduce :
 -  node 8.9.6
 -  yarn 1.5.1
 -  python 3.6.5
 -  changed `"../frappe"` in dependencies in package.json to `"0.0.5"` i.e. the frappejs npm package version i found in the npm site

**Comment by fhbash** [comment]
Here I get these:

$ yarn install
yarn install v1.6.0
[1/4] Resolving packages...
error Package "frappe-datatable" refers to a non-existing file '"/home/fellipeh/teste/datatable"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by jaffreyjoy** [comment]
Its working on ubuntu now

**Comment by sundanny26** [comment]
https://github.com/frappe/accounting/issues/33#issuecomment-384433053
How was this solved ?

**Comment by Jaffrey98** [comment]
In windows just install `windows-build-tools`.
