### ISSUE TITLE
Linux appimage referencing a non-existent folder

### ISSUE THREAD

**Issue by PlaidDroid** [frappe/books#348]
<h2>Description</h2>
Getting this error when trying to setup new organization. There's no folder '../fixtures/verified'.

Version: <b>v0.3.0-beta.0</b>
Package: <b>AppImage</b>

<h2>Error Info</h2>

**Error**: _Error: Error invoking remote method 'get-coa-list': Error: ENOENT: no such file or directory, scandir '/home/plaiddroid/Documents/Programs/fixtures/verified'_

**Stack**:
```
Error: Error invoking remote method 'get-coa-list': Error: ENOENT: no such file or directory, scandir '/home/plaiddroid/Documents/Programs/fixtures/verified'
    at i.invoke (node:electron/js2c/renderer_init:65:526)
    at async EventEmitter.invoke (app://./js/index.2ec1cb6b.js:6:174544)
    at async te (app://./js/index.2ec1cb6b.js:1:14243)
    at async Proxy.formula (app://./js/index.2ec1cb6b.js:1:245203)
    at async Proxy.getValueFromFormula (app://./js/index.2ec1cb6b.js:6:162184)
    at async Proxy.applyFormula (app://./js/index.2ec1cb6b.js:6:161839)
    at async Proxy.applyChange (app://./js/index.2ec1cb6b.js:6:156820)
    at async Proxy.set (app://./js/index.2ec1cb6b.js:6:156718)
```

**Comment by 18alantom** [comment]
Released the fix https://github.com/frappe/books/releases/tag/v0.3.0-beta.1
