### ISSUE TITLE
why this error occuring agian again when currency code is same

### ISSUE THREAD

**Issue by abhijain2003** [frappe/books#387]
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _Error: invalid currency code 'INR '_

**Stack**:
```
Error: invalid currency code 'INR '
    at j (app://./js/chunk-vendors.0752cf3e.js:9:85441)
    at te.currency (app://./js/chunk-vendors.0752cf3e.js:9:90888)
    at new te (app://./js/chunk-vendors.0752cf3e.js:9:90184)
    at ie (app://./js/chunk-vendors.0752cf3e.js:9:93945)
    at f.pesa (app://./js/chunk-vendors.0752cf3e.js:9:94067)
    at U (app://./js/index.86a3a5e3.js:1:13718)
    at xn (app://./js/index.86a3a5e3.js:6:20460)
    at Proxy.submit (app://./js/index.86a3a5e3.js:6:24774)
    at Proxy.handlePrimary (app://./js/index.86a3a5e3.js:6:24308)
    at _n (app://./js/chunk-vendors.0752cf3e.js:521:221207)
```

**Comment by 18alantom** [comment]
This is cause of the white space in INR, i.e. `'INR '` not `'INR'`. Check the field where you may have entered it.

Will add a fix to trim whitespaces.

**Comment by 18alantom** [comment]
done here: https://github.com/frappe/books/pull/381
