### ISSUE TITLE
ERROR  TypeError: Cannot read properties of undefined (reading 'NormalModule')

### ISSUE THREAD

**Issue by louwers** [frappe/books#400]
Reproduction: clone repo, `npm install`, `npm build`.

Node v16.15.0

**Comment by louwers** [comment]
```
 ERROR  TypeError: Cannot read properties of undefined (reading 'NormalModule')
TypeError: Cannot read properties of undefined (reading 'NormalModule')
    at VueLoaderPlugin.apply (/home/bart/src/books/node_modules/vue-loader-v16/dist/pluginWebpack5.js:44:47)
    at webpack (/home/bart/src/books/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:51:13)
    at /home/bart/src/books/node_modules/@vue/cli-service/lib/commands/build/index.js:200:5
    at new Promise (<anonymous>)
    at build (/home/bart/src/books/node_modules/@vue/cli-service/lib/commands/build/index.js:199:10)
    at async /home/bart/src/books/node_modules/@vue/cli-service/lib/commands/build/index.js:89:7
```

**Comment by 18alantom** [comment]
Hey, @louwers can you try it using `yarn`, the build command is `yarn electron:build`. 


Closing this cause `npm` isn't used, let me know if you face issues with `yarn`.
