### ISSUE TITLE
Frappe-Books-0.6.1-beta.0

### ISSUE THREAD

**Issue by magombe** [frappe/books#432]
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _NotFoundError: Not Found: Account Rounded Off_

**Stack**:
```
NotFoundError: Not Found: Account Rounded Off
    at i.load (app://./js/index.0e127820.js:1:501429)
    at async W.getDoc (app://./js/index.0e127820.js:1:482653)
    at async m.loadLink (app://./js/index.0e127820.js:1:502006)
    at async m.loadLinks (app://./js/index.0e127820.js:1:501776)
    at async m.load (app://./js/index.0e127820.js:1:501524)
    at async W.getDoc (app://./js/index.0e127820.js:1:482653)
    at async W (app://./js/index.0e127820.js:7:17201)
    at async q (app://./js/index.0e127820.js:7:17110)
    at async Proxy.showSetupWizardOrDesk (app://./js/index.0e127820.js:1:191127)
    at async Proxy.fileSelected (app://./js/index.0e127820.js:1:190809)
```

**Version**: `0.6.1-beta.0`
**Platform**: `win32`
**Path**: `/index.html`

**Comment by 18alantom** [comment]
![Screen Shot 2022-07-28 at 13 27 13](https://user-images.githubusercontent.com/29507195/181452954-2764466a-64ee-4b91-8d14-79cae64c25fe.png)

The Rounded Off Account can be set in the Settings. This has been handled in https://github.com/frappe/books/pull/434
