### ISSUE TITLE
Error happens on launch, macos

### ISSUE THREAD

**Issue by orangecoloured** [frappe/books#444]
<h2>Description</h2>
This happens on launch

<h2>Error Info</h2>

**Error**: _NotFoundError: Not Found: Account Rounded Off_

**Stack**:
```
NotFoundError: Not Found: Account Rounded Off
    at i.load (app://./js/index.0b1e3334.js:1:502453)
    at async q.getDoc (app://./js/index.0b1e3334.js:1:483457)
    at async m.loadLink (app://./js/index.0b1e3334.js:1:503030)
    at async m.loadLinks (app://./js/index.0b1e3334.js:1:502800)
    at async m.load (app://./js/index.0b1e3334.js:1:502548)
    at async q.getDoc (app://./js/index.0b1e3334.js:1:483457)
    at async q (app://./js/index.0b1e3334.js:7:17206)
    at async W (app://./js/index.0b1e3334.js:7:17115)
    at async Proxy.showSetupWizardOrDesk (app://./js/index.0b1e3334.js:1:191924)
    at async Proxy.fileSelected (app://./js/index.0b1e3334.js:1:191606)
```

**Version**: `0.6.2-beta.0`
**Platform**: `darwin`
**Path**: `/index.html`

**Comment by 18alantom** [comment]
Should be fixed in: [v0.6.3-beta.0](https://github.com/frappe/books/releases/tag/v0.6.3-beta.0)

**Comment by orangecoloured** [comment]
@18alantom 

I installed the latest version and got the error again.

**Error**: _NotFoundError: Not Found: Account Rounded Off_

**Stack**:
```
NotFoundError: Not Found: Account Rounded Off
    at i.load (app://./js/index.d3d57f10.js:1:502811)
    at async q.getDoc (app://./js/index.d3d57f10.js:1:483815)
    at async m.loadLink (app://./js/index.d3d57f10.js:1:503388)
    at async m.loadLinks (app://./js/index.d3d57f10.js:1:503158)
    at async m.load (app://./js/index.d3d57f10.js:1:502906)
    at async q.getDoc (app://./js/index.d3d57f10.js:1:483815)
    at async q (app://./js/index.d3d57f10.js:7:17206)
    at async W (app://./js/index.d3d57f10.js:7:17115)
    at async Proxy.showSetupWizardOrDesk (app://./js/index.d3d57f10.js:1:191937)
    at async Proxy.fileSelected (app://./js/index.d3d57f10.js:1:191619)
```

**Version**: `0.6.3-beta.0`
**Platform**: `darwin`
**Path**: `/index.html`
**Language**: `undefined`
**Country**: `md`

**Comment by 18alantom** [comment]
@orangecoloured I'm unable to recreate this error.

On creating a new instance, the **Round Off Account** gets set to **Round Off** if the Chart of Accounts selected is the Standard Chart of Accounts.
![Screen Shot 2022-08-16 at 14 50 39](https://user-images.githubusercontent.com/29507195/184844882-54955bd1-34fa-465a-a52d-292fcc9ce681.png)

Can you give me steps to recreate this? Which Chart of Accounts have you selected?

**Comment by orangecoloured** [comment]
Here what it looks like

https://user-images.githubusercontent.com/3314891/184854757-4d0e94b9-7714-4d1d-b5da-88ada0205960.mov

**Comment by 18alantom** [comment]
@orangecoloured thanks, I've added a patch (https://github.com/frappe/books/commit/5185820a32f6f7459e845611382c61f275b78bf1) to fix it that'll be out in the next release.

You can fix the issue by either removing the **Round Off Account** value or setting it to **Round Off** under the General settings:
![Screen Shot 2022-08-16 at 17 04 31](https://user-images.githubusercontent.com/29507195/184870009-16a7aaa3-894a-46d3-bb2c-794a3ae03676.png)

**Comment by orangecoloured** [comment]
@18alantom perfect! This fixed it.
