### ISSUE TITLE
LANGUAGE ERROR

### ISSUE THREAD

**Issue by amutahar20002** [frappe/books#446]
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _TypeError: Cannot read properties of undefined (reading 'rootType')_

**Stack**:
```
TypeError: Cannot read properties of undefined (reading 'rootType')
    at Proxy._getGroupedByDateRanges (app://./js/index.7fd7f5e4.js:1:431746)
    at async Proxy.setReportData (app://./js/index.7fd7f5e4.js:1:437506)
    at async Proxy.setReportData (app://./js/index.7fd7f5e4.js:1:346071)
    at async Proxy.activated (app://./js/index.7fd7f5e4.js:1:345141)
```

**Version**: `0.5.0-beta.0`
**Path**: `/report/BalanceSheet`

**Comment by 18alantom** [comment]
This should be fixed now. https://github.com/frappe/books/commit/8d4669a8786584fbc8655b7137324d5a5f67ee74
