### ISSUE TITLE
Frappe books error

### ISSUE THREAD

**Issue by csdindia07** [frappe/books#460]
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _Error: Error invoking remote method 'check-for-updates': Error: ENOENT: no such file or directory, open '/opt/Frappe Books/resources/app-update.yml'_

**Stack**:
```
Error: Error invoking remote method 'check-for-updates': Error: ENOENT: no such file or directory, open '/opt/Frappe Books/resources/app-update.yml'
    at o.invoke (node:electron/js2c/renderer_init:57:526)
    at async EventEmitter.invoke (app://./js/index.3e97c35f.js:7:55577)
    at async l (app://./js/index.3e97c35f.js:1:86997)
    at async Proxy.setDesk (app://./js/index.3e97c35f.js:1:191240)
    at async Proxy.showSetupWizardOrDesk (app://./js/index.3e97c35f.js:1:191973)
    at async Proxy.fileSelected (app://./js/index.3e97c35f.js:1:191619)
    at async Proxy.mounted (app://./js/index.3e97c35f.js:1:191024)
```

**Version**: `0.6.3-beta.0`
**Platform**: `linux`
**Path**: `/get-started`
**Language**: `undefined`
**Country**: `in`

**Comment by 18alantom** [comment]
Fixed in https://github.com/frappe/books/pull/457 should reflect in the next release.
