### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by sathninduk** [frappe/books#487]
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _DatabaseError: Error
The module '/Users/sathnindu/Develop/self/frappebooks/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 103. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)._

**Stack**:
```
Error: The module '/Users/sathnindu/Develop/self/frappebooks/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
    at Object.raw (/Users/sathnindu/Develop/self/frappebooks/node_modules/knex/lib/knex-builder/make-knex.js:115:30)
    at Function.value (/Users/sathnindu/Develop/self/frappebooks/node_modules/knex/lib/knex-builder/make-knex.js:91:29)
    at DatabaseCore.connect (webpack:///./backend/database/core.ts?:81:25)
    at DatabaseManager._connect (webpack:///./backend/database/manager.ts?:47:23)
    at DatabaseManager.connectToDatabase (webpack:///./backend/database/manager.ts?:40:34)
    at DatabaseManager.createNewDatabase (webpack:///./backend/database/manager.ts?:37:27)
    at async dbFunc (webpack:///./main/registerIpcMainActionListeners.ts?:124:20)
```

**Version**: `0.7.0`
**Platform**: `darwin`
**Path**: `/`
**Language**: `undefined`

**Comment by 18alantom** [comment]
Electron's node is different from regular node, you will have to run `electron-rebuild` so that 
`better-sqlite3` is built against the correct version.

Check `package.json` script `postinstall`.
