### ISSUE TITLE
Settings not open

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/books#507]
<h2>Description</h2>

runtime-core.esm-bundler.js:226 ReferenceError: fyo is not defined
    at Proxy.data (Settings.vue:68:11)
    at Tt (runtime-core.esm-bundler.js:3387:34)
    at Or (runtime-core.esm-bundler.js:7309:9)
    at xr (runtime-core.esm-bundler.js:7220:9)
    at br (runtime-core.esm-bundler.js:7142:11)
    at V (runtime-core.esm-bundler.js:5491:13)
    at P (runtime-core.esm-bundler.js:5466:17)
    at v (runtime-core.esm-bundler.js:5068:21)
    at j.u [as fn] (runtime-core.esm-bundler.js:5678:17)
    at j.run (reactivity.esm-bundler.js:185:25)

![Screenshot 2022-12-13 at 4 12 36 PM](https://user-images.githubusercontent.com/973676/207296495-3be346e1-c733-4f46-ae2e-1e8eafca6ad0.png)

**Version**: `0.8.0-beta.0`
**Platform**: `darwin`
**Path**: `/settings`
**Language**: `undefined`
**Country**: `in`

**Comment by 18alantom** [comment]
fixed: https://github.com/frappe/books/commit/ff8b5431f51469c72dbfd0122b0888cd9ee82afb
