### ISSUE TITLE
Cannot open saved db file

### ISSUE THREAD

**Issue by lifeofjer** [frappe/books#553]
<h2>Receive this error</h2>

<h2>Error Info</h2>

**Error**: _NotFoundError: Not Found: Account Write Off_

**Stack**:
```
NotFoundError: Not Found: Account Write Off
    at me.load (app://./js/index.733b9ffb.js:8:476087)
    at async $.getDoc (app://./js/index.733b9ffb.js:8:452698)
    at async ye._loadLinkDoc (app://./js/index.733b9ffb.js:8:476950)
    at async ye._loadLinkField (app://./js/index.733b9ffb.js:8:476749)
    at async ye._loadLink (app://./js/index.733b9ffb.js:8:476570)
    at async ye.loadLinks (app://./js/index.733b9ffb.js:8:476494)
    at async ye.load (app://./js/index.733b9ffb.js:8:476182)
    at async $.getDoc (app://./js/index.733b9ffb.js:8:452698)
    at async xt (app://./js/index.733b9ffb.js:8:40338)
    at async wt (app://./js/index.733b9ffb.js:8:40063)
```

**Version**: `0.9.0`
**Platform**: `darwin`
**Path**: `/index.html`
**Language**: `undefined`
**Country**: `us`

**Comment by lifeofjer** [comment]
Found source of issues:

1) If Inventory features are disabled and a user clears existing "Accounts" that are referenced in the Db table "SingleValue" [for example, I removed the Account Write Off expense to create a new organizational system]
2) I resolved by manually cleaning up the linked data using SQL

May want to add a check for "Inventory" features and further checks for existing linked accounts

**Comment by 18alantom** [comment]
fixed: https://github.com/frappe/books/commit/9864761fe743e7d32ee504a155b1a5c1b3c212b1
