### ISSUE TITLE
Exception not handled

### ISSUE THREAD

**Issue by sodhancha** [frappe/books#563]
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _TypeError: Cannot read properties of undefined (reading 'companyName')_

**Stack**:
```
TypeError: Cannot read properties of undefined (reading 'companyName')
    at h (app://./js/index.733b9ffb.js:1:87166)
    at Proxy.setDesk (app://./js/index.733b9ffb.js:8:112103)
    at async Proxy.showSetupWizardOrDesk (app://./js/index.733b9ffb.js:8:112645)
    at async Proxy.fileSelected (app://./js/index.733b9ffb.js:8:112316)
    at async Proxy.mounted (app://./js/index.733b9ffb.js:8:111602)
```

**Version**: `0.9.0`
**Platform**: `darwin`
**Path**: `/get-started`
**Language**: `undefined`

**Comment by 18alantom** [comment]
Closing this cause, not reproducible and no steps to reproduce provided.
