### ISSUE TITLE
🚨 Error on Serve locally of fresh instance

### ISSUE THREAD

**Issue by ddm21** [frappe/books#665]
<h2>Steps to Reproduce</h2>
No special Steps. Just default Clone and Server

<h2>Info</h2>

**Error**: _DatabaseError: Error
The module '\\?\C:\Users\USERNAME\Desktop\books\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 103. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)._

**Stack**:
```
Error: The module '\\?\C:\Users\dhruv21\Desktop\books\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
    at Object.raw (C:\Users\dhruv21\Desktop\books\node_modules\knex\lib\knex-builder\make-knex.js:115:30)
    at Function.value (C:\Users\dhruv21\Desktop\books\node_modules\knex\lib\knex-builder\make-knex.js:91:29)
    at DatabaseCore.connect (webpack:///./backend/database/core.ts?:81:25)
    at Function.getCountryCode (webpack:///./backend/database/core.ts?:56:18)
    at DatabaseManager._connect (webpack:///./backend/database/manager.ts?:50:139)
    at DatabaseManager.connectToDatabase (webpack:///./backend/database/manager.ts?:45:34)
    at dbFunc (webpack:///./main/registerIpcMainActionListeners.ts?:134:92)
```

**Version**: `0.16.0`
**Platform**: `win32`
**Path**: `/`
**Language**: `undefined`

**Comment by 18alantom** [comment]
@dhruvdalsaniya21 this is cause the installed version of `better-sqlite3` is for Node, not electron node, it needs to be rebuilt for that. Try running the following sequence of commands (if you're using WSL):

```bash
git clone https://github.com/frappe/books --depth 1
cd books

# if using nvm, else just ensure node version > 16.13
nvm use 16 

# install dependencies
yarn

# serve
yarn electron:serve
```

**Note: the command for serving is `yarn electron:serve`**
