### ISSUE TITLE
Address is not a Single Schema

### ISSUE THREAD

**Issue by tanemc876** [frappe/books#727]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _ValidationError: Address is not a Single Schema_

**Stack**:
```
ValidationError: Address is not a Single Schema
    at jH.getDoc (app://assets/index-a76e7a23.js:40:1075)
    at Proxy._loadLinkDoc (app://assets/index-a76e7a23.js:39:2061)
    at Proxy._loadLinkField (app://assets/index-a76e7a23.js:39:1850)
    at Proxy._loadLink (app://assets/index-a76e7a23.js:39:1670)
    at Proxy.loadLinks (app://assets/index-a76e7a23.js:39:1595)
    at Proxy.load (app://assets/index-a76e7a23.js:39:1254)
    at async jH.getDoc (app://assets/index-a76e7a23.js:40:1226)
    at async xAe (app://assets/index-a76e7a23.js:123:11762)
    at async UD (app://assets/index-a76e7a23.js:123:11502)
    at async Proxy.showSetupWizardOrDesk (app://assets/index-a76e7a23.js:123:126880)
```

**Version**: `0.18.0`
**Platform**: `win32`
**Path**: `/index.html`
**Language**: `-`
**Country**: `jm`

**Comment by 18alantom** [comment]
@tanemc876 can you provide steps to reproduce?

**Comment by akshayitzme** [comment]
closing due to lack of response
