### ISSUE TITLE
Don't know what is this error, can anyone help

### ISSUE THREAD

**Issue by Abdullahalaminj** [frappe/books#763]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _ValidationError: invalid doc conversion 'DD-MM-YYYY' of type string found, field: {"label":"Date","fieldname":"date","fieldtype":"Date","section":"Default","tab":"Custom","isCustom":true,"required":true,"default":"DD-MM-YYYY"}_

**Stack**:
```
ValidationError: invalid doc conversion 'DD-MM-YYYY' of type string found, field: {"label":"Date","fieldname":"date","fieldtype":"Date","section":"Default","tab":"Custom","isCustom":true,"required":true,"default":"DD-MM-YYYY"}
    at oi (app://assets/index-037aa12e.js:39:74073)
    at I3 (app://assets/index-037aa12e.js:39:72083)
    at Function.toDocValue (app://assets/index-037aa12e.js:39:70762)
    at Bg.dm (app://assets/index-037aa12e.js:39:71471)
    at Bg.toDocValueMap (app://assets/index-037aa12e.js:39:70525)
    at RG.get (app://assets/index-037aa12e.js:39:75492)
    at async Proxy.load (app://assets/index-037aa12e.js:39:1094)
    at async UH.getDoc (app://assets/index-037aa12e.js:40:1226)
    at async Proxy._loadLinkDoc (app://assets/index-037aa12e.js:39:2042)
    at async Proxy._loadLinkField (app://assets/index-037aa12e.js:39:1839)
```

**Version**: `0.19.0`
**Platform**: `darwin`
**Path**: `/index.html`
**Language**: `-`
**Country**: `ae`

**Comment by RobyCigar** [comment]
what did you do to produce the error?

**Comment by Isaac-GC** [comment]
Hi @Abdullahalaminj,

Are you still encountering this issue in the latest Frappe Books version?

**Comment by akshayitzme** [comment]
@Abdullahalaminj closing this due to lack of response. Please reopen if you  still need assistance with this issue.
