### ISSUE TITLE
Set Template Type error

### ISSUE THREAD

**Issue by tgrignon** [frappe/books#875]
<h2>Description</h2>
When I try to create a new Print Template, I can't set a Type

<h2>Steps to Reproduce</h2>

1. Create a new Template
2. Save or not
3. Click on the toggle (...) and select **Set Template Type**

<h2>Info</h2>

**Error**: _ReferenceError: fyo is not defined_

**Stack**:
```
ReferenceError: fyo is not defined
    at Proxy.df (app://assets/index-c659ca9f.js:113:53222)
    at ad.run (app://assets/index-c659ca9f.js:2:5960)
    at get value [as value] (app://assets/index-c659ca9f.js:2:14580)
    at Object.get [as df] (app://assets/index-c659ca9f.js:5:23435)
    at Object.get (app://assets/index-c659ca9f.js:5:21744)
    at Proxy._ve (app://assets/index-c659ca9f.js:113:53896)
    at pm (app://assets/index-c659ca9f.js:5:4292)
    at ad.be [as fn] (app://assets/index-c659ca9f.js:5:39127)
    at ad.run (app://assets/index-c659ca9f.js:2:5960)
    at Qe.R.update (app://assets/index-c659ca9f.js:5:39420)
```

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/template-builder/New Print Template 02`
**Language**: `English`
**Country**: `ca`

**Comment by ableksaju** [comment]
@tgrignon  I’ve checked the issue on my device, and the Print Template appears to be working correctly. Are you still facing this issue?


<img width="990" alt="Screenshot 2024-08-12 at 12 33 22 PM" src="https://github.com/user-attachments/assets/1dce8ee1-3201-40f6-8c4b-e86f653d83fb">

**Comment by akshayitzme** [comment]
@tgrignon Please try the same in the latest version of FBooks and please reopen if the issue persists.
