### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Slzg** [frappe/books#931]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _TypeError: Cannot read properties of undefined (reading 'companyName')_

**Stack**:
```
TypeError: Cannot read properties of undefined (reading 'companyName')
    at bT (app://assets/index-c659ca9f.js:54:40951)
    at Proxy.setDesk (app://assets/index-c659ca9f.js:127:134990)
    at async Proxy.showSetupWizardOrDesk (app://assets/index-c659ca9f.js:127:135878)
    at async Proxy.fileSelected (app://assets/index-c659ca9f.js:127:135338)
    at async Proxy.setInitialScreen (app://assets/index-c659ca9f.js:127:134632)
    at async Proxy.mounted (app://assets/index-c659ca9f.js:127:134439)
```

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/list/PurchaseInvoice`
**Language**: `English`
**Country**: `kh`

**Comment by ableksaju** [comment]
Could you please give the steps for reproducing it?

**Comment by Slzg** [comment]
I was just on the Purchase Invoice transaction and I did not even open a
document and it just popped up..

**Comment by ableksaju** [comment]
Could you please check if the issue persists after restarting the application?

**Comment by akshayitzme** [comment]
Couldn't reproduce, closing due to inactivity.
