### ISSUE TITLE
Getting issue on yarn build

### ISSUE THREAD

**Issue by lokichaulagain** [frappe/books#944]
### Summary

`✓ built in 25.76s
  • electron-builder  version=24.9.1 os=10.0.22631
  • writing effective config  file=dist_electron\bundled\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=better-sqlite3@9.3.0 platform=win32 arch=x64
  • install prebuilt binary  name=better-sqlite3 version=9.3.0 platform=win32 arch=x64 napi=
  • build native dependency from sources  name=better-sqlite3
                                          version=9.3.0
                                          platform=win32
                                          arch=x64
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 7.1.1
    prebuild-install warn install prebuilt binaries enforced with --force!
    prebuild-install warn install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds\better-sqlite3-v9.3.0-electron-v110-win32-x64.tar.gz
    prebuild-install info looking for cached prebuild @ C:\Users\loken\AppData\Roaming\npm-cache\_prebuilds\919997-better-sqlite3-v9.3.0-electron-v110-win32-x64.tar.gz
    prebuild-install info found cached prebuild
    prebuild-install info unpacking @ C:\Users\loken\AppData\Roaming\npm-cache\_prebuilds\919997-better-sqlite3-v9.3.0-electron-v110-win32-x64.tar.gz
    prebuild-install warn install EBUSY: resource busy or locked, open 'C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\better-sqlite3\build\Release\better_sqlite3.node'    

  • rebuilding native dependency  name=better-sqlite3 version=9.3.0
  ⨯ cannot execute  cause=exit status 1
$ prebuild-install || node-gyp rebuild --release
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=prebuild-install warn install EBUSY: resource busy or locked, open 'C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
    gyp info it worked if it ends with ok
    gyp info using node-gyp@9.1.0
    gyp info using node@20.9.0 | win32 | x64
    gyp ERR! clean error
    gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
    gyp ERR! System Windows_NT 10.0.22631
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\loken\\Downloads\\books-0.22.0\\books-0.22.0\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\better-sqlite3
    gyp ERR! node -v v20.9.0
    gyp ERR! node-gyp -v v9.1.0
    gyp ERR! not ok
error Command failed with exit code 1.

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\loken\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js' run install
                    workingDir=C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\better-sqlite3

C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\builder-util\src\util.ts:251
      reject(new ExecError(command, code, out, errorOut))
             ^
Error: C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
2
    at ChildProcess.<anonymous> (C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.cp.emit (C:\Users\loken\Downloads\books-0.22.0\books-0.22.0\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\loken\Downloads\books-0.22.0\books-0.22.0> `
![image](https://github.com/user-attachments/assets/730ae7c7-0026-4d36-960b-fc38f07a779f)

**Comment by lokichaulagain** [comment]
I resolved the issue after a day. The problem was due to the lack of administrator privileges. The yarn build command succeeded after running VS Code with administrator privileges.
I solved it from this [Github issue](https://github.com/Schniz/fnm/issues/338).
